name: CI/CD FastAPI Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: bryanmiomi/fastapi-app:latest

    - name: Analyze with Docker Scout
      uses: docker/scout-action@v1
      with:
        command: cves
        image: bryanmiomi/fastapi-app:latest
        sarif-file: results.sarif
